### ISSUE TITLE
import nmcli  return a error

### ISSUE THREAD

**Issue by yingchengpa** [ushiboy/nmcli#20]
pip3 install nmcli , succesfully installed nmcli-0.3.0  in centos  7.8.2003 . 

then, when I import nmcli,  has a error:

~~~
test.py

import nmcli

print(nmcli.device())
~~~
return a error : ' Parse failed []
I usr the cmd nmcli d :
~~~
[root@localhost network]# nmcli d

DEVICE       TYPE      STATE      CONNECTION

ens224       ethernet  connected  ens224

ens192       ethernet  connected  ens192

virbr0       bridge    connected  virbr0

docker0      bridge    unmanaged  --

veth877582a  ethernet  unmanaged  --

lo           loopback  unmanaged  --

virbr0-nic   tun       unmanaged  --
~~~

**Comment by yingchengpa** [comment]
I have find the reason, the fix like this in _device.py line51 :
~~~
for row in r.split('\n')[1:]:
    if row != '':       # add 
        results.append(Device.parse(row))
~~~
I print(r) in _device.py line 49,  it shows a blank line in the last line:
~~~
[root@localhost network]# python3 network.py
DEVICE       TYPE      STATE      CONNECTION
ens224       ethernet  connected  ens224
ens192       ethernet  connected  ens192
virbr0       bridge    connected  virbr0
docker0      bridge    unmanaged  --
veth877582a  ethernet  unmanaged  --
lo           loopback  unmanaged  --
virbr0-nic   tun       unmanaged  --

Traceback (most recent call last):
  File "network.py", line 10, in <module>
    print(nmcli.device())
  File "/usr/local/python3.8.1/lib/python3.8/site-packages/nmcli/_device.py", line 45, in __call__
    return self.status()
  File "/usr/local/python3.8.1/lib/python3.8/site-packages/nmcli/_device.py", line 52, in status
    results.append(Device.parse(row))
  File "/usr/local/python3.8.1/lib/python3.8/site-packages/nmcli/data/device.py", line 30, in parse
    raise ValueError('Parse failed [%s]' % text)
ValueError: Parse failed []
~~~

**Comment by ushiboy** [comment]
Thanks for the feedback.
Version 0.3.1 has been released, try it out.
