### ISSUE TITLE
Error occurs with nmcli.general() on nmcli client version 1.48.x

### ISSUE THREAD

**Issue by ushiboy** [ushiboy/nmcli#71]
In nmcli client version 1.48.x, using nmcli.general() fails with the following error and does not work.

Pull request URL that led to the discovery: https://github.com/ushiboy/nmcli/pull/70

nmcli client version: `1.48.10-1`

```
$ python app.py 
Traceback (most recent call last):
  File "/home/pi/app/app.py", line 3, in <module>
    print(nmcli.general())
          ^^^^^^^^^^^^^^^
  File "/home/pi/app/venv/lib/python3.12/site-packages/nmcli/_general.py", line 26, in __call__
    return self.status()
           ^^^^^^^^^^^^^
  File "/home/pi/app/venv/lib/python3.12/site-packages/nmcli/_general.py", line 30, in status
    return General.parse(r.split('\n')[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/app/venv/lib/python3.12/site-packages/nmcli/data/general.py", line 34, in parse
    return General(NetworkManagerState(state),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'connected  full          enabled' is not a valid NetworkManagerState
```

**Comment by ushiboy** [comment]
Resolved in version 1.4.0.
